services:
  - type: web
    name: amazon-wallet-backend
    env: docker
    rootDir: backend
    plan: starter
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: amazon_wallet_monitor
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_TTL
        value: 15m
      - key: JWT_REFRESH_TTL
        value: 7d
      - key: CREDENTIALS_ENCRYPTION_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false

